version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:12.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
    postgres:
